FROM 684138814448.dkr.ecr.eu-west-1.amazonaws.com/eas-base:latest

ENV APP_NAME=eas-api
ENV VENV=$VENV_ROOT/$APP_NAME

# Create root directory and clone repos
RUN git clone --depth 1 https://github.com/alphagov/emergency-alerts-utils.git $APP_ROOT/emergency-alerts-utils
RUN git clone --depth 1 https://github.com/alphagov/emergency-alerts-api.git $APP_ROOT/emergency-alerts-api

# Copy configuration files
COPY config/api/ $APP_ROOT/emergency-alerts-api/

# Build emergency-alerts-utils
RUN $PYTHON_VERSION -m venv $VENV_ROOT/eas-utils
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && make bootstrap

# Run emergency-alerts-api
RUN $PYTHON_VERSION -m venv $VENV
RUN cd $APP_ROOT/emergency-alerts-api && . $VENV/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-api && . $VENV/bin/activate && make bootstrap
RUN cp $APP_ROOT/emergency-alerts-api/app/config.py $APP_ROOT/emergency-alerts-api/app/config.py.bak && cat $APP_ROOT/emergency-alerts-api/app/config.py.bak | sed -e 's/NOTIFY_EMAIL_DOMAIN.*."notify.tools"/NOTIFY_EMAIL_DOMAIN = "fujitsu.com"/' -e "s/NOTIFY_EMAIL_DOMAIN.*.'notify.tools'/NOTIFY_EMAIL_DOMAIN = 'fujitsu.com'/" > $APP_ROOT/emergency-alerts-api/app/config.py

# CMD bash $APP_ROOT/start.sh $APP_NAME
CMD . /venv/eas-api/bin/activate && cd /eas/emergency-alerts-api && . /eas/emergency-alerts-api/environment.sh && flask db upgrade && flask run -p 6011 --host=0.0.0.0
EXPOSE 6011
