FROM 684138814448.dkr.ecr.eu-west-1.amazonaws.com/eas-base:latest

ENV APP_NAME=eas-admin
ENV VENV=$VENV_ROOT/$APP_NAME

# Create root directory and clone repos
RUN git clone --depth 1 https://github.com/alphagov/emergency-alerts-utils.git $APP_ROOT/emergency-alerts-utils
RUN git clone -b EAS-470-decoupled-config --depth 1 https://github.com/alphagov/emergency-alerts-admin.git $APP_ROOT/emergency-alerts-admin

# Copy configuration files
COPY config/admin/ $APP_ROOT/emergency-alerts-admin/

# Build emergency-alerts-utils
RUN $PYTHON_VERSION -m venv $VENV_ROOT/eas-utils
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && make bootstrap

# Run emergency-alerts-admin
RUN $PYTHON_VERSION -m venv $VENV
RUN cd $APP_ROOT/emergency-alerts-admin && . $VENV/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-admin && . $VENV/bin/activate && make bootstrap
RUN echo 'fujitsu.com' >> $APP_ROOT/emergency-alerts-admin/app/utils/email_domains.txt

# CMD bash $APP_ROOT/start.sh $APP_NAME
CMD . /venv/eas-admin/bin/activate && cd /eas/emergency-alerts-admin && . /eas/emergency-alerts-admin/environment.sh && flask run -p 6012 --host=0.0.0.0
EXPOSE 6012
