FROM 684138814448.dkr.ecr.eu-west-1.amazonaws.com/eas-base:latest

ENV APP_NAME=eas-celery
ENV VENV=$VENV_ROOT/$APP_NAME

# Create root directory and clone repos
RUN git clone --depth 1 https://github.com/alphagov/emergency-alerts-utils.git $APP_ROOT/emergency-alerts-utils
RUN git clone --depth 1 https://github.com/alphagov/emergency-alerts-api.git $APP_ROOT/emergency-alerts-api

# Copy service file
COPY resources/$APP_NAME.service /etc/systemd/system

# Copy configuration files
COPY config/api/ $APP_ROOT/emergency-alerts-api/

# Copy startup script
COPY resources/start.sh $APP_ROOT/$APP_NAME/

# Build emergency-alerts-utils
RUN $PYTHON_VERSION -m venv $VENV_ROOT/eas-utils
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-utils && . $VENV_ROOT/eas-utils/bin/activate && make bootstrap

# Run emergency-alerts-api
RUN $PYTHON_VERSION -m venv $VENV
RUN cd $APP_ROOT/emergency-alerts-api && . $VENV/bin/activate && pip3 install wheel && pip3 install pycurl
RUN cd $APP_ROOT/emergency-alerts-api && . $VENV/bin/activate && make bootstrap

CMD bash $APP_ROOT/$APP_NAME/start.sh $APP_NAME
EXPOSE 8125
