FROM 684138814448.dkr.ecr.eu-west-1.amazonaws.com/eas-base:latest

# Install Postgresql.
RUN apt-get install lsb-release -y && curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg && echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
RUN apt-get update -y; apt-get install postgresql-11 libpq-dev -y

# Copy postgresql configuration file
COPY config/postgres/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
COPY config/postgres/postgresql.conf /etc/postgresql/11/main/postgresql.conf

# Copy database seed dump
COPY resources/database_seed.dmp $APP_ROOT/
COPY resources/startdb.sh $APP_ROOT/

# Change to postgres user and seed database
USER postgres

RUN service postgresql start && \
  psql -c 'CREATE ROLE ubuntu LOGIN CREATEDB;' && \
  psql -c 'CREATE ROLE root LOGIN CREATEDB;' && \
  psql -c 'CREATE DATABASE emergency_alerts;' && \
  psql emergency_alerts < $APP_ROOT/database_seed.dmp

USER root

CMD bash $APP_ROOT/startdb.sh && tail -F /var/log/journal/*
EXPOSE 5432
